# fly.toml app configuration file generated for valheim-agent-brain on 2024-06-03T12:49:55-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'valheim-agent-brain'
primary_region = 'sjc'

[build]
  builder = 'paketobuildpacks/builder:base'

[env]
  PORT = '8080'
  WEBSOCKET_PORT = '8765'

[[services]]
  internal_port = 8080
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  [[services.ports]]
    port = 80
    handlers = ["http"]
  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

[[vm]]
  cpu_kind = 'performance'
  cpus = 1
  size = "performance-1x"
  memory = "2gb"
